### ISSUE TITLE
Country versus Worldwide discrepancy

### ISSUE THREAD

**Issue by matt77hias** [lauripiispanen/most-active-github-users-counter#16]
I actually discovered your [site](https://commits.top) by accident while browsing the web, and noticed a discrepancy in the rankings. Apparently, I am the most active user in Belgian (*makes me wonder what I have done so far with my life* 😉), while at the same time I am not being ranked in the Worldwide table.

This seems kind of odd given the fact that I am not an astronaut (yet) and given the minor difference between the corresponding search queries. The (pseudo) search query for Belgium is basically the same as the (pseudo) search query for Worldwide with the exception of an additional filter.

**Comment by lauripiispanen** [comment]
Yup, looks like you have some 32 which likely means your account won’t make it past the initial filter (sort by followers). This sorting by followers is necessary, since unfortunately the GitHub API doesn’t allow sorting by number of contributions. The reasoning being that people who have many followers are more likely to have many contributions as well.
