### ISSUE TITLE
Amount of considered users prevents users from being listed

### ISSUE THREAD

**Issue by IchHabRecht** [lauripiispanen/most-active-github-users-counter#2]
I guess due to the limitation of considered users, not all people have the chance to be listed in your list. There should be added some note, that the list is not complete.

**Comment by lauripiispanen** [comment]
Yes, this is due to GitHub API not offering a direct method to sort by number of contributions. As shown in the pseudocode example, the script sorts according to followers first and then takes the top 1000 (max number allowed by GitHub API):

```
githubUsers.sort(_.followers)
           .filter(_.location == 'Finland') 
           .take(1000)
           .sort(_.contributions)
           .take(256)
```

 It is thus possible to have more contributions and still not make it to the list. Sorry.
