### ISSUE TITLE
No mention of a man with 3500 commits

### ISSUE THREAD

**Issue by IamManchanda** [lauripiispanen/most-active-github-users-counter#26]
I don't see myself https://github.com/IamManchanda
neither in https://commits.top/worldwide.html
nor in https://commits.top/india.html

**Comment by IamManchanda** [comment]
this might be case that your presets don't have `new delhi` ... I just changed it to `delhi` in my profile
Still can't see but that's maybe because the last server refresh was on 17th september ... will be looking for update

**Comment by lauripiispanen** [comment]
GitHub location search is text-based, so `delhi` covers `new delhi`. You missing from the list is likely due to lower amount of followers than is required. Unfortunately GitHub searches cannot be sorted directly by contributions, so the search is first sorted by followers and then by contributions. While not ideal, it is more likely for people with more followers to have more contributions as well (there's an extremely long tail of people with none or very little contributions).

**Comment by DanielRuf** [comment]
> due to lower amount of followers than is required.

Has the algorithm changed? Because top contributors often have less followers.

**Comment by lauripiispanen** [comment]
Nope, the algorithm has been the same for ~1,5 years.
