### ISSUE TITLE
Add filter to show only public commits

### ISSUE THREAD

**Issue by brylie** [lauripiispanen/most-active-github-users-counter#37]
A lot of the top users have many commits in private repos, some with suspiciously many counts. In general, it is hard to verify private commits, which may allow people to "game" the top list.

Please consider adding a filter to show top users with most *public*, verifiable commits.

**Comment by lauripiispanen** [comment]
I’ll need to check the APIs but this may be impossible, as the current contributions counts don’t differentiate between public or private. This thing started as a fun little hobby project so it’s interesting to see that people would actually start to sacrifice their profiles in order to get to the top. 🤔

**Comment by MatissJanis** [comment]
This would definitely be a really nice feature. Some people (myself included) use Github for work, so naturally I have a lot of commits. What would be interesting to see it how I rank up to others on my open-source contributions (public).

**Comment by lauripiispanen** [comment]
Good news! This'll soon be possible. There is indeed a big difference between public and public+private lists. My current plan is to make public contributions the default and showing private contributions an option.

**Comment by lauripiispanen** [comment]
This is now in production
