### ISSUE TITLE
Problem with Organization Ranking Algorithm

### ISSUE THREAD

**Issue by michieriffic** [lauripiispanen/most-active-github-users-counter#66]
@lauripiispanen 
What's the algorithm that you have used for organization? 

Last week, our community - WWCodeManila (github.com/wwcodemanila) was part of top 10 in the Philippines -> https://commits.top/philippines.html

However, today, it wasn't there. Was planning to show this to our community in our upcoming hacktoberfest event.

Updated Changes Example:
No. 4. Coapperative -> https://github.com/coapperative -> Only has 1 commit shown in their repository
No. 6. GatsbyJS -> https://github.com/gatsbyjs (not from the Philippines)

**Can you show total number of commits made by organization instead of members? Thanks.**

**Comment by lauripiispanen** [comment]
Hi! The algorithm basically picks the organization from each user in the top list and then tallies them up. So it basically lists the number of users the organization has in the top list. I'd rather not change the algorithm, since whichever alternative is used is a personal preference and there is no "right algorithm". Organizations per se don't have any commits, but users in the organizations do.
