### ISSUE TITLE
contributions update + calculation issue

### ISSUE THREAD

**Issue by Mudassar045** [lauripiispanen/most-active-github-users-counter#71]
I don't know how frequently the code behind the project pulls the contributions per location. Here are the following questions I would like to ask:

- What is the `refresh period` of the contributions on commits.top?
- How contributions are calculated?

*Note:* Previously I saw my contributions were 650+ on [commits.top](https://commits.top/pakistan.html) (also as same as on GitHub contribution graph), but after 10 days, it's showing 200+

**Comment by lauripiispanen** [comment]
Hi! The contributions are updated once a week. They are what GitHub uses to calculate contributions. The logic was recently changed to separate between public and private contributions, which caused big changes in the rankings. I've now also updated the page template to reflect this. Next data update will pull both public and private contributions and builds pages for both of them, so that you can browse countries and select if you'd like to see public contributions only, or both public+private.
